#!/usr/bin/env bash

#
# 'Packager' is a wrapper around many tools that are able to install/upgrade packages.
#
# It is created in order to be as easy as possible to extend to support more tools.
#
# To add support to a new tool, follow this procedure:
# - Create a script called 'packager-[name of your tool here, can be anything]', and add it to your PATH.
# - Your script should accept all the commands explained below.
#
# COMMANDS of packager tools.
#
# enabled
#   Should exit with an error code of 0 if your tool can be used (is installed on this machine...), or any other code if your tool cannot be used.
#   If the tool cannot be used, should display an explanation in the standard output..
#
# name
#   Should print the description of your tool (eg. 'Racket Package Manager'), without trailing end-of-line character (eg. by using 'echo -n your-name').
#
# install [package1] [package2] [...]
#   Should install the given packages.
#
# upgrade
#   Should upgrade all installed packages.
#
# upgrade [package1] [package2] [...]
#   Should upgrade only the selected packages.
#
# remove [package1] [package2] [...]
#   Should remove the selected packages, but (if applicable), keep their dependencies and configuration.
#
# purge [package1] [package2] [...]
#   Should completely remove the package, any unneeded dependencies, and configuration files.
#
# search [package1] [package2] [...]
#   Should search for a package in the repositories.
#
# You can implement any other command you'd like, if needed. Wrappers are allowed to add their own interactive processes (eg. to ask for confirmation...). For example, it is possible to have a wrapper that asks the user whether 'sudo' should be used or not.
#

if [[ $1 == "complete" ]]; then
	complete -W "install help upgrade search remove v" packager
	return
fi

# region Help

if [[ $1 == "help" || $1 == "--help" ]]; then
	cat <<EOF
packager - Created by Ivan Canet

Description:
    This tool is a wrapper around multiple package managers (pacman, apt...).
    Each packager tool is named 'packager-<name>'.

    When called, this script will first find all possible tools that are
    available on this machine, and will prompt the user to choose which to use.

General syntax:
    packager help
    packager [-v] [options] <COMMAND> [packages...]

Options:
    help            Displays this message.
    -v              Displays debug information.
    --tool TOOL		Use this packager tool instead of ask the user to choose.

Commands:
    i,  install     Installs the given packages.
    u,  upgrade     Upgrades all packages.
                    When packages are specified, only upgrades those (if
                    possible).
    s,  search      Search for informations about a package.
    r,  remove      Prompts whether the user wants to remove or purge packages,
                    then applies the selected option on the given packages.
    p,  purge       Same as 'remove'.
Any other command will be passed to the backend.
EOF
	exit 0
fi

# endregion
# region Verbosity

VERBOSE=0
if [[ $1 == "v" || $1 == "-v" ]]; then
	VERBOSE=1
	shift
fi

function debug() {
	[[ $VERBOSE == 1 ]] && echo "debug: $*"
}

# endregion
# region Dependencies

. ${os_toolkit_import:?}
os_require --caller packager compgen

# endregion
# region Execution

function find-tools() {
	for tool in $(compgen -A command "packager-") $(compgen -A function "packager-"); do
		debug "Tool $tool found."
		if $tool enabled >/dev/null; then
			debug "Tool $tool is enabled."
			TOOLS+=("${tool/packager-/} $($tool name)")
		else
			debug "Tool $tool is disabled (if this is abnormal, run '$tool enabled' to get more information.)."
		fi
	done
}

function select-tool() {
	os_menu --title "Choose your tool:" "${TOOLS[@]}"
	TOOL="packager-${os_menu_answer:?}"
	debug "Selected tool: '$TOOL'."
}

declare -a TOOLS
find-tools

if [[ $1 == "--tool" ]]; then
	os_require --caller packager "$2"
	TOOL="$2"
	shift
	shift
else
	select-tool
fi

function find-command() {
	case $1 in
	install | i)
		COMMAND=install
		;;
	upgrade | u)
		COMMAND=upgrade
		;;
	search | s)
		COMMAND=search
		;;
	remove | r | purge | p)
		os_menu --title "Are you sure you want to completely remove the packages?" \
			"yes Yes, delete everything, including unneeded dependencies and configuration." \
			"keep No, remove the packages but keep the dependencies and configuration." \
			"no No, don't do anything."
		case $os_menu_answer in
		yes)
			COMMAND=purge
			;;
		keep)
			COMMAND=remove
			;;
		no)
			os_info "Stopping."
			exit 0
			;;
		esac
		;;
	*)
		os_info "Unknown command '$1', passing it anyway."
		COMMAND="$1"
		;;
	esac
}

find-command $1
shift

# endregion

$TOOL $COMMAND $*
